---
title: "moz_cholera"
author: "Joao Muianga"
date: "2023-02-01"
output: html_document
---

```{r setup, include=FALSE}

pacman::p_load(learnr,here, rio,openxlsx, remotes, tidyverse,skimr, epikit,       
  lubridate,stringr,base,janitor, gtsummary, corrr, caret,broom,httr,jsonlite,cowplot,          
  RColorBrewer, gghighlight,ggrepel,ggExtra,tsibble, viridis,scales, apyramid,
  rmarkdown,knitr,flextable, incidence2m, frailtypack,  dsr, PHEindicatormethods, officer)


```
# data clean 

```{r}

linelist <- cholera_cases%>%
  filter(Cases >0)%>%
  group_by(Country, Province, District, Year, Week)%>%
  summarise(Cases = sum(Cases, na.rm = T))%>%
  mutate(iso_start_date = as.Date(paste(Year, Week, 1, sep="-"), "%Y-%U-%u"))

linelist_01 <- linelist%>%
  filter(iso_start_date > "2022-11-27")
```
## Plot incident curve for mozambique
```{r}
ggplot(data = linelist)+
  
  geom_histogram(
    mapping = aes(
      x = iso_start_date,           # x-axis is epiweek (as class Date)
      y = Cases,
      binwidth = 7),

    fill = "#2C74B3",
    stat = "identity")+      # this is also required when plotting count data
     
  # labels for x-axis
  scale_x_date(
    date_breaks = "3 weeks",      # labels every 2 months 
    date_labels = '%Y - W%W')+       #labeled by month with year below
  
  theme_minimal()+
    # adjust bold face, and caption position
  theme(
    axis.title.x = element_text(size = 13),    # axis titles larger and bold
    axis.title.y = element_text(size = 13),
    axis.text.x = element_text(size = 11),
    axis.text.y = element_text(size = 12),
    title = element_text(size = 14, face = "bold"),
    plot.caption = element_text(hjust = 0, face = "italic") # move caption to left
  )+
  
  labs(
    x = "Report date", 
    y = "Weekly case incidence",
    title = "Weekly cholera case incidence in Mozambique, as of 26th January, 2023")

  
```






## incident Plot from week 48
```{r}
linelist_1 <- linelist%>%
  filter(iso_start_date > "2022-11-27")

epi_counts_1 <- incidence(              # create weekly incidence object
  linelist,                         # dataset with counts aggregated by day
  date_index = iso_start_date,  # column with dates
  count = Cases,                    # column with counts
  interval = "week",            # aggregate daily counts up to weeks
  groups = Province                 # group by hospital

  )


# plot the weekly incidence epi curve, with stacked bars by hospital
plot(epi_counts_1,                      # incidence object
     fill = Province)                 # color the bars by hospital
```

## Plot incident curve by district 

```{r pressure, echo=FALSE}
# A plot with facets by district
ggplot(linelist_01, aes(x = iso_start_date, y = Cases)) +
  geom_col(width = 1, fill = "#5c7dba") +       # plot the count data as columns
  theme_minimal()+                              # simplify the background panels
  labs(                                         # add plot labels, title, etc.
    x = "Date of report",
    y = "Weekly cholera cases",
    title = "Weekly cholera cases by district") +
   # labels for x-axis
  scale_x_date(
    date_breaks = "week",      # labels every 2 months 
    date_labels = '%Y\n /W%W')+       #labeled by month with year below
    theme(
    axis.text.x = element_text(size = 8),
    axis.text.y = element_text(size = 8, face = "bold"),
    plot.caption = element_text(hjust = 0, face = "italic") # move caption to left
  )+
  
  facet_wrap(~District)                       # the facets are created
```

## Plot incident curve by district 

```{r pressure, echo=FALSE}
# A plot with facets by district
ggplot(linelist_1, aes(x = iso_start_date, y = Cases)) +
  geom_col(width = 1, fill = "darkred") +       # plot the count data as columns
  theme_minimal()+                              # simplify the background panels
  labs(                                         # add plot labels, title, etc.
    x = "Date of report",
    y = "Cholera cases",
    title = "Weekly cholera cases by district") +
  facet_wrap(~District)                       # the facets are created
```


```{r pressure, echo=FALSE}
install.packages("glue")
library("glue")
crf_chol<-crf_cholera%>%
  mutate(cumulatives_deaths = as.numeric(cumulatives_deaths),
         cumulative_cases   = as.numeric(cumulative_cases),
         first_case_reported = as.Date(`first case reported`),
         last_case_reported = as.Date(`last case reported`))


crf_chol_1 <- crf_chol%>%
  mutate(crf_ptg = 100*(cumulatives_deaths/cumulative_cases))

crf_chol_2 <- crf_chol_1%>%
  mutate(crf_ptg = round(crf_ptg, digits = 2))

crf_chol_3 <- crf_chol_2%>%
  dplyr::select(province, district, first_case_reported, cumulative_cases, cumulatives_deaths, crf_ptg,last_week)

###############
moz_case_cum <-  crf_chol_3 %>%  group_by(province, district, first_case_reported, last_week) %>%  
  summarise(
        case_cum = sum(cumulative_cases, na.rm = TRUE),
        death_cum = sum(cumulatives_deaths, na.rm = TRUE)
    ) %>% ungroup()%>%    # Calculate percent change in the last 7 days compared to the previous 7 days    
 
   mutate(
        cfr_cum = death_cum / case_cum) %>% 
  mutate(
        cfr_cum_95ll = cfr_cum - 1.96*sqrt(cfr_cum*(1-cfr_cum)/case_cum),
        cfr_cum_95ul = cfr_cum + 1.96*sqrt(cfr_cum*(1-cfr_cum)/case_cum)
    )%>% 
mutate(
    cfr_cum_lbl = glue("{round(cfr_cum*100,1)} ({round(cfr_cum_95ll*100,1)}, {round(cfr_cum_95ul*100,1)})")
  )

# replace negative values with zero
moz_case_cum <- moz_case_cum%>%
  mutate(cfr_cum_lbl = recode(cfr_cum_lbl,
                              "4.2 (-3.8, 12.2)" = "4.2 (0, 12.2)",
                              "0.5 (-0.4, 1.4)"  = "0.5 (0, 1.4)",
                              "0.2 (-0.2, 0.6)"  = "0.2 (0, 0.6)"))





```


```{r pressure, echo=FALSE}
my_table <- moz_case_cum%>%dplyr::select(province, district, first_case_reported, case_cum, death_cum,  last_week, cfr_cum_lbl)%>%
  flextable()%>%autofit()

my_table <- my_table%>%
  width(j = 1, width = 1.8)%>%
  width(j = 2, width = 1.8)%>%
  width(j = c(3,4,5,6,7), width = 1.6)

my_table <- my_table%>%
  add_header_row(
    top = TRUE,
    values = c("Province",
               "District",
               "First week reported",
               "Cumulatives",
               "",
               "Cases reported last week",
               "CFR(%) Cumulative (95% CI)"
               ))%>%
  set_header_labels(
    province = "",
    district = "",
    first_case_reported = "",
    case_cum = "Cases",
    death_cum = "Deaths",
    last_week = "",
    cfr_cum_lbl = ""
  )%>%
  merge_at(i = 1, j = 4:5, part = "header")  # Horizontally merge columns 4 to 6 in new header row
 
my_table_1 <- my_table%>%
  border_remove()%>%
  theme_booktabs()%>%
  fontsize(i = 1, size = 12, part = "header") %>%   # adjust font size of header
  bold(i = 1, bold = TRUE, part = "header") %>%     # adjust bold face of header
   bold(i = 2, bold = TRUE, part = "header") %>%     # adjust bold face of header
    # add vertical lines to separate Recovered and Died sections
  vline(part = "all", j = 3) %>%   # at column 2 
  vline(part = "all", j = 5)%>%      # at column 5
  vline(part = "all", j = 6)%>%      # at column 5
  flextable::align(align = "center", j = c(4:6), part = "all")%>%
    merge_at(i = 1:2, j = 1, part = "header") %>% 
    merge_at(i = 1:2, j = 2, part = "header")
```

```{r}

library(forestplot)
moz_case_cum %>%  mutate(mean=cfr_cum*100, 
         lower=cfr_cum_95ll*100, 
         upper=cfr_cum_95ul*100) %>%  dplyr::select(mean, lower, upper, study=district, 
         province, case_cum, death_cum, cfr_cum, cfr_cum_lbl) %>%  forestplot(labeltext=c(province, study, case_cum, death_cum, cfr_cum_lbl),
             boxsize = 0.5,
             line.margin = .1) %>%  fp_set_style(box = "royalblue",
               line = "#999999",
               summary = "royalblue",
               hrz_lines = "#999999",
               txt_gp = fpTxtGp(label = gpar(fontfamily = "sans", col = "#5A5A5A"))) %>%  fp_add_header(province = c("", "Province"),
                study = c("", "District"),
                case_cum = c("Cases", "cumulative")%>%fp_align_center(),
                death_cum = c("Deaths", "cumulative")%>%fp_align_center(),
                cfr_cum_lbl = c("", "CFR% (95%CI)"))
```

